theme: jekyll-theme-slate
title: Hardware Aware Efficient Training
description: Workshop at ICML 2022 test

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  
markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true



