theme: jekyll-theme-cayman
title: Hardware Aware Efficient Training
description: Workshop at ICML 2022


navigation:
  Home: "/index"
  Call for Papers: "/cfp"
 
 markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true
