theme: jekyll-theme-slate
title: Hardware Aware Efficient Training (HAET)
description: Workshop at ICML 2022

navigation:
  Home: "/"
  CfP: "/cfp"
  Challenge: "/challenge"
  Keynotes: "/speakers"
  Organizers: "/organisers"
  Schedule: "/schedule"
  
  
markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true



